spring:
  application:
    name: MushinChoirProject


  datasource:
    url : "jdbc:mysql://localhost:3306/choirdb"
    password :
    username: root
    driver: com.mysql.cj.jdbc.Driver

    spring:
      jpa:
        hibernate:
          ddl-auto: update
        generate-ddl: true
        show-sql: true
        properties:
          hibernate:
            format_sql: true


  logging:
    level:
      org:
        springframework:
          security: TRACE